### ISSUE TITLE
Revamp Delegates

### ISSUE THREAD

**Issue by Phantom139** [PhantomGamesDevelopment/Galactic-2D#19]
This is being pushed to item 1 on the to-do list once programming gets going again when I finish up my ultimate guide project.

@Ragora has created a very easy to use Delegate system (https://github.com/Ragora/EasyDelegate) that can replace the massive header enforced system that we currently have.

This is just a note to strip out the old system in favor of implementing that one right away.

**Comment by Phantom139** [comment]
Alright, so a little update here. I went ahead and did a little cleanup session today on the engine files, particularly with the delegate replacement (57209db), and apparently for some interestingly weird reason, the compiler is having some issues comparing the delegate objects here:

`
void removeTickerInstance(const GalacticFrameTickerDelegate &dele) {
    for (S32 i = 0; i < tickerList.size(); i++) {
        if (tickerList[i].tickerDelegate == dele) {
            tickerList.erase((U32)i);
        }
    }
}
`

In this particular case the compiler is complaining that it cannot perform the comparison operator between GalacticFrameTickerDelegate and const GalacticFrameTickerDelegate &, which are typedef'd as typedef StaticDelegate<bool, F64> GalacticFrameTickerDelegate;

More investigation is needed.

**Comment by Ragora** [comment]
At a quick glance, all I can see is that there is const-ness disparity. I don't actually have a Windows box to build on hand to look at the exact error. Also, you have a spelling error in your include in engineCore.h, line 61: https://github.com/PhantomGamesDevelopment/Galactic-2D/blob/development/Source/EngineCore/engineCore.h#L61

Also, here is the start of a CMakeLists file if it helps at all: http://pastebin.com/SdAsm4tL

I'm also going to note that I discovered a bug in the library's Cached Delegate (deferred calls) implementations, if you had intended on using those. Methods with references in their parameters will cause the CachedDelegate to save stack space variables and thusly pass in garbage when the eventual call is made. This is already fixed on my part by forcing the removal of reference types (using std::remove_reference) so that they are cached by actual value, not reference. My coding is just pending a commit.

Beyond that I have been working at optimizations for the CachedDelegate types, namely by removing the necessity of having to allocate a secondary delegate object and just storing the delegate properties directly.

**Comment by Phantom139** [comment]
Alright, didn't catch that spelling error earlier so thanks for that.

I'm mainly coding in the virtual function overrides for the platform specific code at the moment which is why I haven't really had the opportunity to go and do a full build of the project as of lately to see where there are issues, but that will be a top priority once I finish up the windows platform functions (#21).

As for the upgrades and fixes to the library itself, you do have write access to the repository, so go ahead and install the updates as you see fit, or just let me know when there's a new one to install and I'll take care of it. Just remember that I am leaning more towards using internal engine classes over the standard template library at the moment to ensure full compatibility across all platforms when that time comes.

**Comment by Ragora** [comment]
Most of my proposed changes are in the repo right now: https://github.com/Ragora/EasyDelegate/blob/master/include/easydelegate.hpp

I just need to look over it, update the commenting (for Doxygen) and verify that everything works correctly.

**Comment by Phantom139** [comment]
I'll likely perform the upgrade once I finish up the work with the Cross Platform code as right now, I'd rather focus on that work-load to get it done and out of the way.

As for the latest updates, 5e4bcf3 finished the code sweep to fully integrate the lib into the code-base so things should be all set to go in terms of using it in any additional cases where delegates will be required.

As for the error located on line 114 (https://github.com/PhantomGamesDevelopment/Galactic-2D/blob/development/Source/EngineCore/Tools/frameTicker.h#L114), simply changing the types to match exactly does not please the compiler, so something else seems to be going on.

The error as caught by MSVS IS states: 	

`IntelliSense: no operator "==" matches these operands
            operand types are: Galactic::Core::GalacticFrameTickerDelegate == const Galactic::Core::GalacticFrameTickerDelegate	c:\Users\Owner\Documents\Phantom Games Development\Galactic 2D\Galactic2D\Galactic2D\Source\EngineCore\Tools\frameTicker.h	114	40	Galactic 2D`

Adjusting the types to matches produces the same error. Fixing this up will resolve the final piece as needed by this issue.

**Comment by Ragora** [comment]
There is no way to compare for equality. If you wanted to simply check if they were the *exact* same instance then you could try: if (&tickerList[i].tickerDelegate == &dele) // Compare the pointers

Otherwise, you will need to compare mProcAddress and so on in an == operator definition. I should probably implement this myself in the lib, actually.

**Comment by Phantom139** [comment]
Actually, that's exactly what was needed by the code. The bit there is just running through the list of delegates stored on the main ticker and if it's the matching one (in the event of removeTickerInstance) then it deletes it.

That should work fine in that case, thanks. Commit & Close coming up.

**Comment by Phantom139** [comment]
Final delegate related error associated with the implementation of EasyDelegate has been addressed in 979329b. Closing & marking for future reference.
